X = input(' Digite algo aqui: ')
print(' O tipo primitivo é: ', type(X))
print(' Só tem espaço?', X.isspace())
print(' Só tem número? ', X.isnumeric())
print(' Só tem letra? ', X.isalpha())
print(' É alphanúmerico? ', X.isalnum())
print(' Está em maiúsculo?', X.isupper())
print(' Está em minúsculo?', X.islower())
print(' Está capitalizado?', X.istitle())
